
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe and SingleItemRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

[enabledMappers]
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Add Conversions for the recipes that recolor shulker boxes.
	ShulkerBoxColoringMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Adds Conversions for fluid container items and fluids.
	FluidMapper = true

